packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
  - "tests/*"
  - "tools/*"
enableGlobalVirtualStore: true
hoist: false
confirmModulesPurge: false
allowBuilds:
  appium: false
  edgedriver: false
  esbuild: false
  geckodriver: false
  protobufjs: false
  re2: false
  sharp: false
